spring:
  application:
    name: gen-ai-orchestrator
  profiles:
    active: custom

  ai:
    openai:
      api-key: ignore
      base-url: http://localhost:12434/engines
      chat:
        options:
          model: ai/gpt-oss
    mcp:
      client:
        enabled: true
        stdio:
          connections:
            docker-gateway:
              command: docker
              args: [mcp, gateway, run]