logging:
  level:
    web: DEBUG
  file:
    path: ./logs

spring:
  application:
    name: gen-ai-orchestrator
  profiles:
    active: custom

  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: user
    password: password

  mvc:
    async:
      request-timeout: 600000

  ai:
    openai:
      api-key: ignore
      base-url: http://localhost:12434/engines
      chat:
        options:
          model: ai/qwen3:latest
          temperature: 0.0
      embedding:
        options:
          model: ai/nomic-embed-text-v1.5:latest
    mcp:
      client:
        enabled: true
        stdio:
          connections:
            docker-gateway:
              command: docker
              args: [mcp, gateway, run]
    vectorstore:
      observations:
        log-query-response: true
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
      observations:
        log-prompt: true
        log-completion: true
        include-error-logging: true
      client:
        observations:
          log-prompt: true
          log-completion: true
    tools:
      observations:
        include-content: true
