logging:
  level:
    web: DEBUG
  file:
    path: ./logs

spring:
  application:
    name: gen-ai-orchestrator
  profiles:
    active: custom

  ai:
    openai:
      api-key: ignore
      base-url: http://localhost:12434/engines
      chat:
        options:
          model: ai/gpt-oss
    mcp:
      client:
        enabled: true
        stdio:
          connections:
            docker-gateway:
              command: docker
              args: [mcp, gateway, run]
    chat:
      observations:
        log-prompt: true
        log-completion: true
        include-error-logging: true
      client:
        observations:
          log-prompt: true
          log-completion: true
    tools:
      observations:
        include-content: true